name: Generate sitemap on merge to main
on: [push, pull_request]
# on:
#   push:
#     branches:
#       - main

jobs:
  generate-sitemap:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Call sitemap generation endpoint
        run: curl -X POST "https://ubuntu-com-14900.demos.haus/sitemap_tree.xml"

      - name: Send message on failure
        if: failure()
        run: curl -X POST -F "workflow=${GITHUB_WORKFLOW}" -F "repo_name=${GITHUB_REPOSITORY}" -F "action_id=${GITHUB_RUN_ID}" ${{ secrets.BOT_URL }}?room=web--design