name: Generate sitemap for static pages
on:
  push:
    branches:
      - main
    paths:
      - "templates/**"

jobs:
  generate-sitemap:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Call sitemap generation endpoint
        run: |
          curl -X POST "https://ubuntu.com/sitemap_tree.xml" \
          -H "Authorization: Bearer ${{ secrets.SITEMAP_SECRET }}"